export const tablas = [
  {
    table: "actividadSesion",
    columns: [
      "actividadSesion.idActividadSesion",
      "actividadSesion.fkIdSesionUsuario",
      "actividadSesion.fkIdPermiso",
      "actividadSesion.endpoint",
      "actividadSesion.ip",
    ],
  },
  {
    table: "aseguradoras",
    columns: [
      "aseguradoras.idAseguradora",
      "aseguradoras.nombre",
      "aseguradoras.razonSocial",
      "aseguradoras.rtn",
      "aseguradoras.logo",
      "aseguradoras.direccion",
      "aseguradoras.ciudad",
      "aseguradoras.departamento",
      "aseguradoras.telefono",
      "aseguradoras.correo",
      "aseguradoras.nombreContacto",
      "aseguradoras.telefonoContacto",
      "aseguradoras.correoContacto",
      "aseguradoras.createdBy",
      "aseguradoras.updatedBy",
      "aseguradoras.deletedBy",
      "aseguradoras.deletedAt",
      "aseguradoras.createdAt",
      "aseguradoras.updatedAt",
    ],
  },
  {
    table: "aseguradosDependientes",
    columns: [
      "aseguradosDependientes.idAseguradoDependiente",
      "aseguradosDependientes.fkIdAseguradoPoliza",
      "aseguradosDependientes.fkIdPersona",
      "aseguradosDependientes.createdBy",
      "aseguradosDependientes.updatedBy",
      "aseguradosDependientes.deletedBy",
      "aseguradosDependientes.deletedAt",
      "aseguradosDependientes.createdAt",
      "aseguradosDependientes.updatedAt",
    ],
  },
  {
    table: "aseguradosPolizas",
    columns: [
      "aseguradosPolizas.idAseguradoPoliza",
      "aseguradosPolizas.fkIdPoliza",
      "aseguradosPolizas.fkIdPersona",
      "aseguradosPolizas.createdBy",
      "aseguradosPolizas.updatedBy",
      "aseguradosPolizas.deletedBy",
      "aseguradosPolizas.deletedAt",
      "aseguradosPolizas.createdAt",
      "aseguradosPolizas.updatedAt",
    ],
  },
  {
    table: "bancos",
    columns: [
      "bancos.idBanco",
      "bancos.nombre",
      "bancos.createdBy",
      "bancos.updatedBy",
      "bancos.deletedBy",
      "bancos.deletedAt",
      "bancos.createdAt",
      "bancos.updatedAt",
    ],
  },
  {
    table: "bitacoraReclamos",
    columns: [
      "bitacoraReclamos.idBitacoraReclamo",
      "bitacoraReclamos.fkIdDocumento",
      "bitacoraReclamos.descripcion",
      "bitacoraReclamos.createdBy",
      "bitacoraReclamos.updatedBy",
      "bitacoraReclamos.deletedBy",
      "bitacoraReclamos.deletedAt",
      "bitacoraReclamos.createdAt",
      "bitacoraReclamos.updatedAt",
      "bitacoraReclamos.fkIdEtapa",
      "bitacoraReclamos.fkIdReclamo",
    ],
  },
  {
    table: "coberturas",
    columns: [
      "coberturas.idCobertura",
      "coberturas.fkIdPlanes",
      "coberturas.fkIdTipoCobertura",
      "coberturas.nombre",
      "coberturas.descripcion",
      "coberturas.consultasMaximas",
      "coberturas.createdBy",
      "coberturas.updatedBy",
      "coberturas.deletedBy",
      "coberturas.deletedAt",
      "coberturas.createdAt",
      "coberturas.updatedAt",
    ],
  },
  {
    table: "cuentasBancarias",
    columns: [
      "cuentasBancarias.idCuentaBancaria",
      "cuentasBancarias.fkIdBanco",
      "cuentasBancarias.fkIdTipoCuentaBancaria",
      "cuentasBancarias.numero",
      "cuentasBancarias.createdBy",
      "cuentasBancarias.updatedBy",
      "cuentasBancarias.deletedBy",
      "cuentasBancarias.deletedAt",
      "cuentasBancarias.createdAt",
      "cuentasBancarias.updatedAt",
    ],
  },
  {
    table: "cuentasBancariasPersonas",
    columns: [
      "cuentasBancariasPersonas.idCuentaBancariaPersona",
      "cuentasBancariasPersonas.fkIdPersona",
      "cuentasBancariasPersonas.fkIdCuentaBancaria",
      "cuentasBancariasPersonas.createdBy",
      "cuentasBancariasPersonas.updatedBy",
      "cuentasBancariasPersonas.deletedBy",
      "cuentasBancariasPersonas.deletedAt",
      "cuentasBancariasPersonas.createdAt",
      "cuentasBancariasPersonas.updatedAt",
    ],
  },
  {
    table: "cuentasBancariasProveedores",
    columns: [
      "cuentasBancariasProveedores.idCuentaBancariaProveedores",
      "cuentasBancariasProveedores.fkIdProveedor",
      "cuentasBancariasProveedores.fkIdCuentaBancaria",
      "cuentasBancariasProveedores.createdBy",
      "cuentasBancariasProveedores.updatedBy",
      "cuentasBancariasProveedores.deletedBy",
      "cuentasBancariasProveedores.deletedAt",
      "cuentasBancariasProveedores.createdAt",
      "cuentasBancariasProveedores.updatedAt",
    ],
  },
  {
    table: "diagnosticos",
    columns: [
      "diagnosticos.idDiagnostico",
      "diagnosticos.nombre",
      "diagnosticos.createdBy",
      "diagnosticos.updatedBy",
      "diagnosticos.deletedBy",
      "diagnosticos.deletedAt",
      "diagnosticos.createdAt",
      "diagnosticos.updatedAt",
    ],
  },
  {
    table: "diagnosticosReclamos",
    columns: [
      "diagnosticosReclamos.idDiagnosticoReclamo",
      "diagnosticosReclamos.fkIdReclamo",
      "diagnosticosReclamos.fkIdDiagnostico",
      "diagnosticosReclamos.createdBy",
      "diagnosticosReclamos.updatedBy",
      "diagnosticosReclamos.deletedBy",
      "diagnosticosReclamos.deletedAt",
      "diagnosticosReclamos.createdAt",
      "diagnosticosReclamos.updatedAt",
    ],
  },
  {
    table: "documentos",
    columns: [
      "documentos.idDocumento",
      "documentos.fkIdTipoDocumento",
      "documentos.nombre",
      "documentos.path",
      "documentos.createdBy",
      "documentos.updatedBy",
      "documentos.deletedBy",
      "documentos.deletedAt",
      "documentos.createdAt",
      "documentos.updatedAt",
    ],
  },
  {
    table: "documentosReclamos",
    columns: [
      "documentosReclamos.idDocumentoReclamo",
      "documentosReclamos.fkIdReclamo",
      "documentosReclamos.fkIdDocumento",
      "documentosReclamos.createdBy",
      "documentosReclamos.updatedBy",
      "documentosReclamos.deletedBy",
      "documentosReclamos.deletedAt",
      "documentosReclamos.createdAt",
      "documentosReclamos.updatedAt",
    ],
  },
  {
    table: "estadosPolizas",
    columns: [
      "estadosPolizas.idEstadoPoliza",
      "estadosPolizas.nombre",
      "estadosPolizas.createdBy",
      "estadosPolizas.updatedBy",
      "estadosPolizas.deletedBy",
      "estadosPolizas.deletedAt",
      "estadosPolizas.createdAt",
      "estadosPolizas.updatedAt",
    ],
  },
  {
    table: "etapasReclamos",
    columns: [
      "etapasReclamos.idEtapaReclamo",
      "etapasReclamos.nombre",
      "etapasReclamos.posicion",
      "etapasReclamos.color",
      "etapasReclamos.createdBy",
      "etapasReclamos.updatedBy",
      "etapasReclamos.deletedBy",
      "etapasReclamos.deletedAt",
      "etapasReclamos.createdAt",
      "etapasReclamos.updatedAt",
    ],
  },
  {
    table: "facturas",
    columns: [
      "facturas.idFacturas",
      "facturas.fkIdProveedor",
      "facturas.fkIdDocumento",
      "facturas.numero",
      "facturas.descripcion",
      "facturas.createdBy",
      "facturas.updatedBy",
      "facturas.deletedBy",
      "facturas.deletedAt",
      "facturas.createdAt",
      "facturas.updatedAt",
      "facturas.fkIdReclamo",
    ],
  },
  {
    table: "grupoFamiliar",
    columns: [
      "grupoFamiliar.idGrupoFamiliar",
      "grupoFamiliar.fkIdPersona",
      "grupoFamiliar.fkIdPersonaFamiliar",
      "grupoFamiliar.fkIdParentesco",
      "grupoFamiliar.createdBy",
      "grupoFamiliar.updatedBy",
      "grupoFamiliar.deletedBy",
      "grupoFamiliar.deletedAt",
      "grupoFamiliar.createdAt",
      "grupoFamiliar.updatedAt",
    ],
  },
  {
    table: "metodos",
    columns: ["metodos.idMetodo", "metodos.tipo"],
  },
  {
    table: "migrations",
    columns: ["migrations.id", "migrations.migration", "migrations.batch"],
  },
  {
    table: "parentescos",
    columns: [
      "parentescos.idParentescos",
      "parentescos.nombre",
      "parentescos.createdBy",
      "parentescos.updatedBy",
      "parentescos.deletedBy",
      "parentescos.deletedAt",
      "parentescos.createdAt",
      "parentescos.updatedAt",
    ],
  },
  {
    table: "parentescosOpuestos",
    columns: [
      "parentescosOpuestos.idParentescoOpuesto",
      "parentescosOpuestos.fkIdParentesco",
      "parentescosOpuestos.fkIdParentescoOpuesto",
      "parentescosOpuestos.createdBy",
      "parentescosOpuestos.updatedBy",
      "parentescosOpuestos.deletedBy",
      "parentescosOpuestos.deletedAt",
      "parentescosOpuestos.createdAt",
      "parentescosOpuestos.updatedAt",
    ],
  },
  {
    table: "permisos",
    columns: [
      "permisos.idPermiso",
      "permisos.fkIdMetodo",
      "permisos.nombre",
      "permisos.codigo",
      "permisos.descripcion",
      "permisos.createdBy",
      "permisos.updatedBy",
      "permisos.deletedBy",
      "permisos.deletedAt",
      "permisos.createdAt",
      "permisos.updatedAt",
    ],
  },
  {
    table: "permisosRoles",
    columns: [
      "permisosRoles.idPermisoRol",
      "permisosRoles.fkIdPermiso",
      "permisosRoles.fkIdRol",
      "permisosRoles.createdBy",
      "permisosRoles.updatedBy",
      "permisosRoles.deletedBy",
      "permisosRoles.deletedAt",
      "permisosRoles.createdAt",
      "permisosRoles.updatedAt",
    ],
  },
  {
    table: "personas",
    columns: [
      "personas.idPersonas",
      "personas.uuid",
      "personas.numeroIdentidad",
      "personas.nombres",
      "personas.apellidos",
      "personas.sexo",
      "personas.correo",
      "personas.telefono",
      "personas.createdBy",
      "personas.updatedBy",
      "personas.deletedBy",
      "personas.deletedAt",
      "personas.createdAt",
      "personas.updatedAt",
    ],
  },
  {
    table: "planes",
    columns: [
      "planes.idPlanes",
      "planes.fkIdProducto",
      "planes.nombre",
      "planes.descripcion",
      "planes.codigo",
      "planes.createdBy",
      "planes.updatedBy",
      "planes.deletedBy",
      "planes.deletedAt",
      "planes.createdAt",
      "planes.updatedAt",
    ],
  },
  {
    table: "polizas",
    columns: [
      "polizas.idPoliza",
      "polizas.fkIdPlanes",
      "polizas.fkIdEstadoPoliza",
      "polizas.numero",
      "polizas.vigenciaReclamos",
      "polizas.createdBy",
      "polizas.updatedBy",
      "polizas.deletedBy",
      "polizas.deletedAt",
      "polizas.createdAt",
      "polizas.updatedAt",
    ],
  },
  {
    table: "productos",
    columns: [
      "productos.idProducto",
      "productos.fkIdAseguradora",
      "productos.nombre",
      "productos.descripcion",
      "productos.codigo",
      "productos.fotoUrl",
      "productos.createdBy",
      "productos.updatedBy",
      "productos.deletedBy",
      "productos.deletedAt",
      "productos.createdAt",
      "productos.updatedAt",
    ],
  },
  {
    table: "productosFactura",
    columns: [
      "productosFactura.idProducto",
      "productosFactura.fkIdFactura",
      "productosFactura.fkIdCobertura",
      "productosFactura.fkIdTipoServicio",
      "productosFactura.nombre",
      "productosFactura.cantidad",
      "productosFactura.descripcion",
      "productosFactura.createdBy",
      "productosFactura.updatedBy",
      "productosFactura.deletedBy",
      "productosFactura.deletedAt",
      "productosFactura.createdAt",
      "productosFactura.updatedAt",
    ],
  },
  {
    table: "proveedores",
    columns: [
      "proveedores.idProveedor",
      "proveedores.fkIdTipoProveedor",
      "proveedores.nombre",
      "proveedores.rtn",
      "proveedores.createdBy",
      "proveedores.updatedBy",
      "proveedores.deletedBy",
      "proveedores.deletedAt",
      "proveedores.createdAt",
      "proveedores.updatedAt",
    ],
  },
  {
    table: "reclamos",
    columns: [
      "reclamos.idReclamo",
      "reclamos.fkIdAseguradoPoliza",
      "reclamos.fkIdAseguradoDependiente",
      "reclamos.fkIdPoliza",
      "reclamos.fkIdEtapaReclamo",
      "reclamos.numero",
      "reclamos.motivoBloqueo",
      "reclamos.createdBy",
      "reclamos.updatedBy",
      "reclamos.deletedBy",
      "reclamos.deletedAt",
      "reclamos.createdAt",
      "reclamos.updatedAt",
    ],
  },
  {
    table: "roles",
    columns: [
      "roles.idRol",
      "roles.fkIdSistema",
      "roles.fkIdTipoUsuario",
      "roles.nombre",
      "roles.descripcion",
      "roles.tipo",
      "roles.createdBy",
      "roles.updatedBy",
      "roles.deletedBy",
      "roles.deletedAt",
      "roles.createdAt",
      "roles.updatedAt",
    ],
  },
  {
    table: "seeders",
    columns: [
      "seeders.idSeeder",
      "seeders.nombre",
      "seeders.codigo",
      "seeders.ranAt",
    ],
  },
  {
    table: "sesionesUsuario",
    columns: [
      "sesionesUsuario.idSesionUsuario",
      "sesionesUsuario.fkIdUsuario",
      "sesionesUsuario.tipo",
      "sesionesUsuario.ipAddress",
      "sesionesUsuario.lastActivity",
    ],
  },
  {
    table: "sistemas",
    columns: ["sistemas.idSistema", "sistemas.nombre"],
  },
  {
    table: "tableCoberturas",
    columns: [
      "tableCoberturas.id",
      "tableCoberturas.createdAt",
      "tableCoberturas.updatedAt",
    ],
  },
  {
    table: "tiposCoberturas",
    columns: [
      "tiposCoberturas.idTipoCobertura",
      "tiposCoberturas.nombre",
      "tiposCoberturas.createdBy",
      "tiposCoberturas.updatedBy",
      "tiposCoberturas.deletedBy",
      "tiposCoberturas.deletedAt",
      "tiposCoberturas.createdAt",
      "tiposCoberturas.updatedAt",
    ],
  },
  {
    table: "tiposCuentasBancarias",
    columns: [
      "tiposCuentasBancarias.idTipoCuentaBancaria",
      "tiposCuentasBancarias.nombre",
      "tiposCuentasBancarias.createdBy",
      "tiposCuentasBancarias.updatedBy",
      "tiposCuentasBancarias.deletedBy",
      "tiposCuentasBancarias.deletedAt",
      "tiposCuentasBancarias.createdAt",
      "tiposCuentasBancarias.updatedAt",
    ],
  },
  {
    table: "tiposDocumentos",
    columns: ["tiposDocumentos.idTipoDocumento", "tiposDocumentos.nombre"],
  },
  {
    table: "tiposProveedores",
    columns: [
      "tiposProveedores.idTipoProveedor",
      "tiposProveedores.nombre",
      "tiposProveedores.createdBy",
      "tiposProveedores.updatedBy",
      "tiposProveedores.deletedBy",
      "tiposProveedores.deletedAt",
      "tiposProveedores.createdAt",
      "tiposProveedores.updatedAt",
    ],
  },
  {
    table: "tiposServicios",
    columns: [
      "tiposServicios.idTipoServicio",
      "tiposServicios.nombre",
      "tiposServicios.createdBy",
      "tiposServicios.updatedBy",
      "tiposServicios.deletedBy",
      "tiposServicios.deletedAt",
      "tiposServicios.createdAt",
      "tiposServicios.updatedAt",
    ],
  },
  {
    table: "tiposUsuarios",
    columns: ["tiposUsuarios.idTipoUsuario", "tiposUsuarios.nombre"],
  },
  {
    table: "usuarios",
    columns: [
      "usuarios.idUsuario",
      "usuarios.fkIdRol",
      "usuarios.nombre",
      "usuarios.email",
      "usuarios.password",
      "usuarios.createdBy",
      "usuarios.updatedBy",
      "usuarios.deletedBy",
      "usuarios.deletedAt",
      "usuarios.createdAt",
      "usuarios.updatedAt",
    ],
  },
];
